### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kevung** [kevung/blunderDB#13]
### General

- [x] check variables passed as props in component cannot be deleted and used with existing stores instead
- [x] fix copy position from blunderDB to XG when no analysis --> not a bug, simply an invalid position cannot be imported in XG 
- [x] add mechanism to reset position, statusbar. Currently written hard in newDatabase
- [x] if positionsstore empty, set positionstore to empty position. Set it in subscribe with if condition 
- [x] update, add only from edit mode -> when switch to normal mode, reload existing position so is not a problem if update from normal mode 
- [x] delete totalPositionLengthStore
- [x] fix bug where cannot update position with xg analysis if position already exists : cannot toggle analysis panel with unsaved changes (the case when importing analysis of existing position twice)
- [x] deletePosition redundant initialization code, taken care a priori by positionsStore subscribe
- [x] use loadAllPositions in different functions save, delete, update, openDatabase...
- [x] in loadAllPositions, ensure no redundant code with respect to subscribe store
- [x] after updating analysis, make refresh analysis panel
- [x] replace show variables with stores to toggle visibility of panels, ....
- [x] goto position only in normal mode
- [x] add filter take into account dice: `d` for decision_type, `D` to take account dice number
- [x] cannot go in search panel from toolbar only in edit mode
- [x] fix search text (comma separated) in search modal
- [x] disable toolbar button according to current mode
- [x] fix next buttom toolbar appearance
- [x] if from normal mode, prevent search in command line
- [x] implement multiple text search (commandline + search modal)
- [x] copy paste position and analysis from blunderDB to blunderDB
- [x] add toolbar button in browsing to reload all positions in database
- [x] reset analysisStore when no psoitions in database (through positionsStore subcribe)
- [x] export and parse engine version 
- [x] decactivate board orientation shortcut when comment modal open
- [x] metadata modal: name, email, version, email, date
- [x] add date of creation for a position in comment. date of modification, last time visited.
- [x] gotoposition with command line -> set correctly currentPositionIndexStore
- [x] add tp2 modal fusion side by side of tp2_live tp2_last. same for tp4
- [x] if one score is unlimited, set the other one also to unlimited
- [x] fix application crash when typing escape before opening a database
- [x] display in position metadata (Ctrl-G), met,  tp2_live, gv...
- [x] add filter for specific move (6/1*) : `m"6/1*"` (for all moves), `M"6/1*"` (for the best move)
- [x] track last mode activated. In command mode, if ESC -> go to last mode, ENTER -> NORMAL
- [x] if help modal, steal focus (enable help in command mode)
- [x] after importing new position, metadata of the position is not available
- [x] test metadata position tp, gv value are correct according to scores and cube values
- [x] remove code preventing browsing shortcut in different modal since it has been blocked properly in global shortcuts with isAnyOpenModalStore
- [x] reduire le cas échéant le nombre de chiffres significatifs dans les tableaux tp, gv si arrondis à l'entier
- [x] fix bug tp4_last -5 -7 display N/A
- [x] adapt move pattern to accept single quote also (only double quote currently)
- [x] adapt best move filter to accept "DT", "DP", "ND" as doubling pattern
- [x] make search text and move pattern filters case insensitive
- [x] add filter to sort position by date of modification/visited (command and search modal)
- [x] `e` after a search does not reload all positions
- [x] enable mouse wheel browsing when analysisPanel is open
- [x] check that position add manually have a creation date in analysis
- [x] fix problem window size discrepancy between linux and windows
- [x] fix visual code problems detected
- [x] fix regression tag position does not work anymore
- [x] [windows] fix bug simple manual position inserted: Error saving position and analysis
- [x] ensure position operation are done in the proper mode (NORMAL or EDIT)
- [x] fix regression search by text and best move
- [x] fix conflict between usual filter and search/best move. For ex: if one search best move, "Off", it comes in conflict with "O4,5" opponent checker off
- [x] test filter in search modal
- [x] create a custom icon
- [x] ~~fix regression in checker structure filter~~
- [x] ~~add filter on equity error~~
- [x] ~~add filter contain given move (not only best move)~~
- [x] ~~fix bug next or previous position with j, k, arrow~~
- [x] fix win, gammon, backgammon filter so that W/G/B is always the opponent, and not the player different from the one on roll (otherwise, if opponent is on roll, G is main player...). Opponent is always up
- [x] fix copy paste from blunderDB to XG
- [x] fix copy paste from XG to blunderDB, cubeless equities for doubling decision, fonctionne pas en français (it works in Windows VM from Linux Host blunderDB)
- [x] add config file and make some parameters consistents (such as window dimensions). See https://github.com/wailsapp/wails/issues/1956
- [x] parse XG comments to insert them directly in blunderDB comment section
- [x] fix Windows app smaller dimension size problem. See https://github.com/wailsapp/wails/issues/3260
- [x] fix bug filter decision_type (with search panel). Review all filters
- [x] fix bug search modal empty structure does not find all positions (only those with player1 on roll) 
- [x] fix bug, same filters command line or search modal does not find same positions
- [x] modify backchecker filter to 24 - 19
- [x] build doc in French and english in pdf, un releases and inside the doc as download 
- [x] reduce comment section font and size, make same size as analysis panel
- [x] describe better pip count filter. Precise the pipcount convention (positive for behind in the race, negative for before in the race)
- [ ] try to implement erasing bar checkers by clicking in the center
- [x] add support for other language than English and French (the different languages given by XG).
- [x] new feature to export filtered positions into new database (COMMAND  w, ou NORMAL Ctrl-S)
- [x] new feature to merge a given db into current opened db. 
- [x] parse XG match data (players, date, PR, moves ...) to import a match with drag and drop
- [x] mirror structure filter
- [x] add blot in outfield filter from 18 to 7
- [x] add blot in jan filter from 6 to 1
- [x] add non contact filter
- [ ] implement in EDIT mode a checker structure filter layer system (by default 1/1). When mousewheel, add a new layer (2/2) for checker structure. When search make the union of all the checker structure filters, and apply global filter in addition
- [ ] implement search validation in search modal when Enter key is pressed
- [x] implement GNU position/analysis import
- [x] create filter library (alias -> filter): help, doc, toolbar. Use in command mode. Layout. Update database scheme
- [x] create filter history 
- [x] add a comprehensive filter example section to show how to use command line
- [ ] password protected + crypt
- [ ] fix bug changing die face value, sensibility region is different from drawing die rectangle
- [ ] fix bug browsing j k : have to press twice the key . Seems not to work on certain host
- [x] make documentation display wide (too narrow)
- [x] restore Mac archive release in ci
- [x] fix mac ci : reintroduce ditto step to produce app with correct launching 
- [x] maj ci pour build libwebkit2gtk-4.0 : cf https://github.com/kevung/blunderDB/issues/26
- [x] black dice for player 1? --> abandonned because draw too much attention
- [x] increase comment font or put it in a configuration file
- [x] put parsing logic to backend (gnuid from lolpanda, xg, internal format)
- [ ] fix bug comment1: tag a position, and tag is applied on n-1 position
- [ ] fix bug comment: when brwosing with comment panel opened (scrollwheel in particular)
- [ ] add config parameters to custom board, checkers, cube, dice colors
- [x] enable to swap player
- [ ] fix bug wrong point label when bearoff on the left. Seems to be a problem with xgid (to be confirmed...)
- [ ] add auto complétion in command mode
- [ ] add tuto mode
- [x] export position as png
- [x] update description of toc in doc
- [x] fix already existing position message displayed too shortly
- [ ] add id position filter (to make chapter more easily)
- [x] check cube display layout. Lolpanda strange display 
- [x] update help about macos install 
- [x] add BG Blitz support ? (Message Ibrah). See multiple file example from Daniel mail 
- [x] add a command to toggle pipcount 
- [x] fix library filter bug (edit, ctrl-b, add) Error loading filters: SQL logic error: no such table: filter_library 
- [ ] verify potential shortcut bug with Ctrl- shortcut on Azerty
- [x] export and import comments between blunderDB instances
- [x] add an arrow feature, that imported positions from XG can be 
visualized. Eg after hitting CTRL+L and choosing a move.
- [x] add database import
- [x] improve checker move arrow drawing (for example, start the arrow from checker to be played and not the pip number to avoid overlap)
- [x] add button to save last search as a filter in filter library (enable to save filter without knowing command line filters)
- [x] keep search history (store from searches)
- [x] add EPC calculator using Gnubg bearoff EPC 
- [x] add turnament panel (trophy icon)
- [x] create CLI interface for main blunderDB feature (import for example to enable headless batch mode)
- [x] MacOS Sequoia 15.7.1. error message like "blunderDB-macos-0.9.0.app-The app cannot be opened because it is corrupted or incomplete. (works with users: D.S. not with P. )
- [x] tournament manager (player review entries)
- [x] ajouter un panneau de collections de positions (demande Tristan pour faire des cours), avec fonctionnalité de déplacement des positions, copie, colle, supression. Possibilité avec fonction d'export d'exporter uniquement une ou plusieurs collections spécifiques
- [x] add gnubg match parsing in blunderDB
- [x] add match export in database export 
- [x] add copy, paste match in clipboard
- [x] show last search and last position when opening a database
- [x] verify that stats are always displayed for player on roll (checker or cube move)
- [x] verify delete match delete all information position, analysis, etc... out of the database
- [x] verify correct info position score, cube ... of positions after match import in match mode and normal mode
- [x] update dependencies version (go, npm, vite ...)
- [x] force adding .db to file name when creating a new database, if it does not already finish by .db
- [x] prevent navigation shortcut in export database modal
- [x] exported database cannot be opened : `[Error] Error opening file dialog: – "sql: no rows in result set" openDatabase (App.svelte:810)`
- [x] cannot import xg files (not listed) in opened database
- [x] enable pip mode, and arrows in match mode
- [x] add blunder/error filter 
- [ ] add profile/stats panel (chart icon)
- [ ] add parsing heroes position from clipboard 
- [ ] add parsing for remaining xg and bgblitz languages
- [ ] Add blunderDB translations (en, fr, de, jp, fi, ...) maybe in a new configuration panel
- [x] implémenter le drag/drop de matchs, ou de base de données, ou de text match
- [x] fix English translation in documentation (section 5.9 for example)
- [x] add option to filter inside current searched positions in filter library 
- [x] (see how it interacts with preceding item) add command flag and option in search modal to search in current searched positions 
- [x] Erase checker structure automatically when swiching into EDIT mode.
- [x] add match or tournament filters (to search positions in specific match/tournament)
- [x] add xgp position file import (Wolfgang mail)
- [x] add comment import from xg files
- [ ] implement the possibility to load and deal with extra large database (15Go). Introduce maybe strategy loading only part of data, and aggregation of results. RAM limitation
- [x] add column in match and tournament panels, which displays for each row the related PR and MWC loss
- [x] add way to unify or merge players with name variants
- [ ] fix PR / MWC computation for cube decision. You should check that PR match is equal to what is displayed in xg
- [ ] cube decision played are not properly highlighted
- [ ] stat panel, fix PR par match graph
- [ ] fix positive equity error bug
- [ ] intégrer dans commande cachée les formules EPCs?

### Help

- [x] manual
- [x] about
- [x] update and translate existing doc
- [x] describe modal window for take point, gammon value, met, ... in manual and command mode
- [x] some fixes : a software, menu bar -> toolbar, backward checker, IHM -> interface 
- [x] add a section in faq about virus detection and false positive (take links from reddit discussion)
- [x] fix parsing xg data with xg in english but from a French OS

### Drawing
- [x] supplementary checkers >5 to draw
- ~~[ ] flip players~~ annulé car cas d'usage pas clair
- [x] change board orientation 7900318
- [x] change score
- [x] change player on roll
- [x] change dice or set as cube action
- [x] When no position, show initial position from positionStore
- [x] When deleting position, also delete analysis
- [x] Prevent focus change with Tab on main area, otherwise, it blocks the app and cannot toggle edit mode
- [x] erase position when backspace
- [x] Prevent mouse selection when double click in normal mode?
- [ ] import xgid, position files, match via cli

### DB

- [x] main requests with filters: number, or range, >=x, <=x, =x
- [x]  force cube : `cube`, `cub`, `cu`, `c`
- [x] force score : `score`, `sco`. `sc, `s`
- ~~[ ] blunder~~
- [x] win, gammon, backgammon : `w`, `g`, `b`, `W`, `G`, `B`
- [x] pipcount advance range : `p` 
- [x] player1 absolute pipcount
- [x] checkeroff player1 player2 : `o`, `O`
- [x] backchecker player1 player2 : `k`, `K` 
- [x] checker in the zone player 1 player 2 : `z`, `Z`
- [x] comment, keywords : `#`
- [x] introduce version number to make incompatible compatibility scheme: application version; database version (to decouple application evolution and database scheme)
// do it first via GUI button, and then command mode

### CMD

- [x] comment with `co`, `comment`
- [x] tags with `# key1 key2`
- [x] take point, gammon value

### GUI

- [x] Analysis panel
- [x] Search window (with all its filters)
- [ ] drag and drop database or position file 
- [x] disable context menu
- [x] take point, gammon values
- [x] update help (command in particular)

### ANKI

- [x] create and implement anki mode

### Bugs

- [ ] fix windows error launch smartscreen (see Philippe M. email 28 February).maybe free windows store dev account
- [x] fix MacOs blunderDB opening error with XML file (see D. simon fix email 26 February, 28 February). Maybe add some tests on GitHub MacOs runners. Apply patch mail (name executable)
- [x] fix Bgblitz match import bug (see D. Simon data db and match file email 26 February)
- [x] fix bug import Raphaël cf mail 30/03/1992

**Comment by kevung** [comment]
XGID=bA----D-C---dE---d-e----B-:0:0:1:00:0:0:3:0:10

X:Joueur 1   O:Joueur 2
Le score est X:0 O:0. Partie illimitée, Jacoby Beaver
 +13-14-15-16-17-18------19-20-21-22-23-24-+
 | X           O    |   | O              X |
 | X           O    |   | O              X |
 | X           O    |   | O                |
 | X           O    |   | O                |
 | X                |   | O                |
 |                  |BAR|                  |
 |                  | O |                  |
 | O                | O | X                |
 | O           X    |   | X                |
 | O           X    |   | X                |
 | O           X    |   | X              X |
 +12-11-10--9--8--7-------6--5--4--3--2--1-+
Course  X: 162  O: 164 X-O: 0-0
Videau: 1
X: lance ou double

Analysé avec XG Roller++
Chance de gain du joueur: 54.09% (G:20.06% B:0.47%)
Chance de gain de l'adversaire: 45.91% (G:12.14% B:0.58%)

Equités sans videau: Pas de double=+0.160, Double=+0.324

Equités avec videau
       Pas de double: +0.224
       Double/Beaver: -0.021 (-0.245)
       Double/Passe:  +1.000 (+0.776)

Meilleur action du videau: Pas de double / Beaver
Pourcentage de passes incorrectes pour rendre la décision de double correcte: 24.0%

eXtreme Gammon Version: 2.19.211.pre-release

- [x] make import beaver position correct

> **Fixed** (commit `c10d4244`): the GUI clipboard parser already handled Jacoby/Beaver since 2026-04-20; the remaining gap was `domain.DecodeXGID` (headless server / CLI) which skipped field 7 and returned `HasJacoby=0 HasBeaver=0`. It now decodes field 7 as a money-game bitmask (1=Jacoby, 2=Beaver, 3=both), restoring CLI/GUI parity. Covered by `TestDecodeXGIDJacobyBeaver`.

**Comment by kevung** [comment]
[XGID=-A-BCBBB-c---bB---cbcaAa--0016.txt](https://github.com/user-attachments/files/18416877/XGID.-A-BCBBB-c---bB---cbcaAa--0016.txt)

**Comment by kevung** [comment]
Master TODO clos. Tous les éléments terminés sont archivés ci-dessus. Les éléments restants (parqués en ⏸️ Standby) ont été transformés en issues dédiées :

- #59 — Handle extra-large databases (~15 GB): partial loading + result aggregation
- #60 — Analyse existing filters and propose categories from the *501 Backgammon Problems*
- #61 — Parse Heroes positions from the clipboard
- #62 — Windows SmartScreen warning on launch (SignPath OSS, blocked on application)

**Comment by kevung** [comment]
**Anti-régression : test de contrat de décodage XGID** (branche `fix/xgid-decode-beaver-jacoby`)

La cause racine du bug beaver était la **duplication du parsing XGID** : un décodeur Go (`domain.DecodeXGID`, chemin serveur/CLI) et un parseur JS (`parsePosition`, collage GUI), qui dérivent indépendamment.

Mise en place d'un **corpus partagé** `testdata/xgid_corpus.json`, vérifié par les deux côtés :
- `pkg/blunderdb/domain/xgid_contract_test.go` (Go)
- `frontend/src/__tests__/xgidContract.test.js` (Vitest)

Toute divergence future sur les champs dérivés de l'XGID (cube, dés, score, on-roll, jacoby/beaver) fait échouer un test d'au moins un côté.

En construisant ce corpus, une **seconde divergence** a été révélée et corrigée : `DecodeXGID` stockait la valeur de videau réelle (`1<<v`) au lieu de l'exposant log2 utilisé partout ailleurs (GUI, `ingest/xgmap.go`, hash Zobrist canonique). Un videau décodé via le serveur était donc mal hashé/affiché (videau centré → 2 au lieu de 1). Corrigé.

À terme (cf. discussion) : faire que le GUI appelle un parseur backend unique plutôt que de maintenir deux implémentations.
